services:
  postgres:
    image: postgres:18
    container_name: apextick-postgres
    environment:
      POSTGRES_DB: apextick
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eta8827
    ports:
      - "5440:5432"
    volumes:
      - apextick_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d apextick"]
      interval: 5s
      timeout: 3s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    container_name: apextick-keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - apextick_keycloak_data:/opt/keycloak/data

  booking-service:
    build: ./booking-service
    container_name: apextick-booking
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/apextick
    ports:
      - "8081:8081"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: apextick-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: apextick
      RABBITMQ_DEFAULT_PASS: apextick
    ports:
      - "5672:5672"     # AMQP — your services connect here
      - "15672:15672"   # management UI — you open this in a browser
  
  redis:
    image: redis:7-alpine
    container_name: apextick-redis
    command: redis-server --notify-keyspace-events Ex
    ports:
      - "6379:6379"
      
volumes:
  apextick_pgdata:
  apextick_keycloak_data:

