--liquibase formatted sql

--changeset apextick:003-01-series
CREATE TABLE series (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  short_name VARCHAR(128),
  sport VARCHAR(16) NOT NULL,
  tint VARCHAR(16),
  kicker VARCHAR(128),
  blurb TEXT,
  story TEXT,
  image VARCHAR(255),
  mobile_hero_image VARCHAR(255),
  currency VARCHAR(3) NOT NULL,
  currency_symbol VARCHAR(8),
  cities TEXT,
  scale VARCHAR(64),
  CONSTRAINT uq_series_slug UNIQUE (slug)
);
--rollback DROP TABLE series;

--changeset apextick:003-02-teams
CREATE TABLE teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sport VARCHAR(16) NOT NULL,
  name VARCHAR(255) NOT NULL,
  short_code VARCHAR(16) NOT NULL,
  monogram VARCHAR(8),
  color VARCHAR(16),
  flag VARCHAR(16),
  logo VARCHAR(255),
  CONSTRAINT uq_teams_sport_code UNIQUE (sport, short_code)
);
--rollback DROP TABLE teams;

--changeset apextick:003-03-events-columns
ALTER TABLE events ADD COLUMN slug VARCHAR(128);
ALTER TABLE events ADD COLUMN series_id BIGINT;
ALTER TABLE events ADD COLUMN sport VARCHAR(16);
ALTER TABLE events ADD COLUMN home_team_id BIGINT;
ALTER TABLE events ADD COLUMN away_team_id BIGINT;
ALTER TABLE events ADD COLUMN time_zone VARCHAR(64) NOT NULL DEFAULT 'UTC';
ALTER TABLE events ADD COLUMN city VARCHAR(128);
ALTER TABLE events ADD COLUMN country VARCHAR(128);
ALTER TABLE events ADD COLUMN stage VARCHAR(128);
ALTER TABLE events ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'ONSALE';
ALTER TABLE events ADD COLUMN image VARCHAR(255);
ALTER TABLE events ADD COLUMN blurb TEXT;
ALTER TABLE events ADD COLUMN currency VARCHAR(3) NOT NULL DEFAULT 'USD';
ALTER TABLE events ADD COLUMN sales_start_at TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN sales_end_at TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN created_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE events ADD COLUMN updated_at TIMESTAMPTZ;
ALTER TABLE events ADD CONSTRAINT fk_events_series FOREIGN KEY (series_id) REFERENCES series(id);
ALTER TABLE events ADD CONSTRAINT fk_events_home FOREIGN KEY (home_team_id) REFERENCES teams(id);
ALTER TABLE events ADD CONSTRAINT fk_events_away FOREIGN KEY (away_team_id) REFERENCES teams(id);
--rollback ALTER TABLE events DROP COLUMN slug, DROP COLUMN series_id, DROP COLUMN sport, DROP COLUMN home_team_id, DROP COLUMN away_team_id, DROP COLUMN time_zone, DROP COLUMN city, DROP COLUMN country, DROP COLUMN stage, DROP COLUMN status, DROP COLUMN image, DROP COLUMN blurb, DROP COLUMN currency, DROP COLUMN sales_start_at, DROP COLUMN sales_end_at, DROP COLUMN created_at, DROP COLUMN updated_at;

--changeset apextick:003-04-price-tiers
CREATE TABLE price_tiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(128) NOT NULL,
  price NUMERIC(12,2) NOT NULL,
  perks TEXT,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_tiers_event FOREIGN KEY (event_id) REFERENCES events(id),
  CONSTRAINT uq_tiers_event_code UNIQUE (event_id, code)
);
CREATE INDEX idx_tiers_event ON price_tiers(event_id);
--rollback DROP TABLE price_tiers;

--changeset apextick:003-05-sections
CREATE TABLE sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(128) NOT NULL,
  tier_id BIGINT NOT NULL,
  side VARCHAR(1) NOT NULL,
  row_count INT NOT NULL,
  seats_per_row INT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_sections_event FOREIGN KEY (event_id) REFERENCES events(id),
  CONSTRAINT fk_sections_tier FOREIGN KEY (tier_id) REFERENCES price_tiers(id),
  CONSTRAINT uq_sections_event_code UNIQUE (event_id, code)
);
CREATE INDEX idx_sections_event ON sections(event_id);
--rollback DROP TABLE sections;

--changeset apextick:003-06-seats-columns
ALTER TABLE seats ADD COLUMN section_id BIGINT;
ALTER TABLE seats ADD COLUMN row_idx INT;
ALTER TABLE seats ADD COLUMN col_idx INT;
ALTER TABLE seats ADD CONSTRAINT fk_seats_section FOREIGN KEY (section_id) REFERENCES sections(id);
CREATE INDEX idx_seats_section_status ON seats(section_id, status);
CREATE INDEX idx_seats_held_by ON seats(held_by);
CREATE INDEX idx_seats_held_until ON seats(held_until) WHERE status = 'HELD';
--rollback ALTER TABLE seats DROP COLUMN section_id, DROP COLUMN row_idx, DROP COLUMN col_idx;
