--liquibase formatted sql

--changeset apextick:007-01-orders
CREATE TABLE orders (
  id UUID PRIMARY KEY,
  order_number VARCHAR(16) NOT NULL,
  user_sub VARCHAR(64) NOT NULL,
  user_email VARCHAR(255),
  user_name VARCHAR(255),
  event_id BIGINT NOT NULL REFERENCES events(id),
  status VARCHAR(24) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL,
  fee NUMERIC(12,2) NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  expires_at TIMESTAMPTZ,
  paid_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  cancel_reason VARCHAR(32),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uq_orders_number UNIQUE (order_number),
  CONSTRAINT uq_orders_idem UNIQUE (user_sub, idempotency_key)
);
CREATE INDEX idx_orders_user ON orders (user_sub, created_at DESC);
CREATE INDEX idx_orders_status_expiry ON orders (status, expires_at);
CREATE INDEX idx_orders_event ON orders (event_id);
--rollback DROP TABLE orders;

--changeset apextick:007-02-order-items
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id),
  seat_id BIGINT NOT NULL REFERENCES seats(id),
  seat_label VARCHAR(20) NOT NULL,
  section_name VARCHAR(128) NOT NULL,
  tier_code VARCHAR(32) NOT NULL,
  tier_name VARCHAR(128) NOT NULL,
  unit_price NUMERIC(12,2) NOT NULL,
  CONSTRAINT uq_order_items_seat UNIQUE (order_id, seat_id)
);
CREATE INDEX idx_order_items_order ON order_items (order_id);
CREATE INDEX idx_order_items_seat ON order_items (seat_id);
--rollback DROP TABLE order_items;
