--liquibase formatted sql

--changeset apextick:008-01-payments
CREATE TABLE payments (
  id UUID PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id),
  provider VARCHAR(16) NOT NULL,
  status VARCHAR(24) NOT NULL,
  amount NUMERIC(12,2) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  idempotency_key VARCHAR(128),
  provider_ref VARCHAR(128),
  client_secret VARCHAR(512),
  card_brand VARCHAR(24),
  card_last4 VARCHAR(4),
  failure_code VARCHAR(64),
  failure_message VARCHAR(255),
  raw_result TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ
);
CREATE INDEX idx_payments_order ON payments (order_id);
CREATE UNIQUE INDEX uq_payments_provider_ref ON payments (provider, provider_ref) WHERE provider_ref IS NOT NULL;
--rollback DROP TABLE payments;

--changeset apextick:008-02-payment-webhook-events
CREATE TABLE payment_webhook_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(16) NOT NULL,
  external_event_id VARCHAR(128) NOT NULL,
  payload TEXT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ,
  outcome VARCHAR(32),
  CONSTRAINT uq_webhook_provider_event UNIQUE (provider, external_event_id)
);
--rollback DROP TABLE payment_webhook_events;

--changeset apextick:008-03-tickets
CREATE TABLE tickets (
  id UUID PRIMARY KEY,
  order_id UUID NOT NULL REFERENCES orders(id),
  order_item_id BIGINT NOT NULL REFERENCES order_items(id),
  event_id BIGINT NOT NULL REFERENCES events(id),
  seat_id BIGINT NOT NULL REFERENCES seats(id),
  qr_token VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL,
  issued_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  used_by VARCHAR(64),
  s3_key VARCHAR(255),
  pdf_generated_at TIMESTAMPTZ,
  CONSTRAINT uq_tickets_order_item UNIQUE (order_item_id),
  CONSTRAINT uq_tickets_qr UNIQUE (qr_token)
);
CREATE INDEX idx_tickets_order ON tickets (order_id);
CREATE INDEX idx_tickets_event_status ON tickets (event_id, status);
--rollback DROP TABLE tickets;
