--liquibase formatted sql

--changeset apextick:011-01-ticket-scans
-- Every scan at a gate, admitted or turned away, and every admission undone. Until now the
-- only trace of who came through was a USED flag with one timestamp, and the only head count
-- lived in a single browser tab until it reloaded: no figure across turnstiles for capacity
-- or safety, and nothing to go back to when a steward says they scanned the wrong phone.
-- event_id is the event the gate was admitting, which a wrong-event scan does not share with
-- its ticket.
CREATE TABLE ticket_scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id UUID NOT NULL REFERENCES tickets(id),
  event_id BIGINT NOT NULL REFERENCES events(id),
  outcome VARCHAR(32) NOT NULL,
  gate VARCHAR(64),
  actor_sub VARCHAR(64) NOT NULL,
  reason VARCHAR(255),
  scanned_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ticket_scans_ticket ON ticket_scans (ticket_id, scanned_at);
CREATE INDEX idx_ticket_scans_event ON ticket_scans (event_id, scanned_at);
ALTER TABLE tickets ADD COLUMN used_gate VARCHAR(64);
--rollback ALTER TABLE tickets DROP COLUMN used_gate; DROP TABLE ticket_scans;
